gui:
  nerdFontsVersion: "3"
os:
  editCommand: "nvim"
  editCommandTemplate: '{{editor}} --server /tmp/nvim-server.pipe --remote-tab "$(pwd)/{{filename}}"'
keybinding:
  universal:
    prevItem-alt: l
    nextItem-alt: k
    prevBlock-alt: j
    nextBlock-alt: ;
    undo: u
    redo: U
